### ISSUE TITLE
Error: Proxy error: Could not proxy request /auth/google from localhost:3000 to http://localhost:5000 (ECONNREFUSED).

### ISSUE THREAD

**Issue by YashovardhanSiramdas** [Zerone-IIITDM/samgatha-2018#1]
Proxy error while opening Login Page.

nodejs error:-
ECONNREFUSED

![screenshot from 2018-01-17 11-26-05](https://user-images.githubusercontent.com/33130821/35028059-0913d36a-fb7a-11e7-8156-7895c6c5a80f.png)

**Comment by pranay414** [comment]
In `client/src` directory look for **package.json** and then navigate to **proxy**. Change the proxy target for `/auth/google` to **127.0.0.1:5000**.
